services:
  - type: web
    name: greenexpress
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: GreenExpress
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://greenexpress-administration.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
